apiVersion: v1
kind: Service
metadata:
  name: spring-app-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      nodePort: 30080  # Hardcoding for local easy access
  selector:
    app: spring-app
