apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"spring-service","namespace":"default"},"spec":{"ports":[{"nodePort":30001,"port":8080,"targetPort":8080}],"selector":{"app":"spring-hello"},"type":"NodePort"}}
  creationTimestamp: "2026-03-29T19:33:00Z"
  name: spring-service
  namespace: default
  resourceVersion: "1239"
  uid: 145cd842-2b22-4101-a7e8-72e5427e307f
spec:
  clusterIP: 10.106.30.191
  clusterIPs:
  - 10.106.30.191
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30001
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-hello
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
